project:
  type: website
  output-dir: docs

website:
  title: "achsah-jojo-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Myself"
      - href: portfolio_part_one/part_one.qmd
        text: "Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

